title: "Remote theme example"
remote_theme: pmarsceill/just-the-docs
#color_scheme: "dark"
color_scheme: nil
search_enabled: true

Navigation:
- title: Home
 url: /index.html
- title: About
url: http://xociety.co
 - title: Contact
url: /contact
